import json
import numpy as np
import torch
from transformers import pipeline
import os


class InferlessPythonModel:

    # replace ##task_type## and ##huggingface_name## with appropriate values
    def initialize(self):
        folder_path = os.environ.get('MODEL_WEIGHTS_DIR')
        self.generator = pipeline("text-generation", folder_path ,device=0)

    def download_weights(self):
        folder_path = os.environ.get('MODEL_WEIGHTS_DIR')
        print("folder_path in download weights-->", folder_path, flush=True)
        text_generator = pipeline("text-generation", model="EleutherAI/gpt-neo-125M",device=0)
        text_generator.save_pretrained(folder_path)
        print("download weights called", flush=True)
        
    # inputs is a dictonary where the keys are input names and values are actual input data
    # e.g. in the below code the input name is prompt 
    # The output generated by the infer function should be a dictonary where keys are output names and values are actual output data
    # e.g. in the below code the output name is generated_txt
    def infer(self, inputs):
        prompt = inputs["prompt"]
        pipeline_output = self.generator(prompt, do_sample=True, min_length=20)
        generated_txt = pipeline_output[0]["generated_text"]
        return {"generated_text": "sample output-develop-11"}

    # perform any cleanup activity here
    def finalize(self,args):
        self.pipe = None
